USE [MinistryPlatform]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = '[dbo].[cr_Destinations]'))
BEGIN
	CREATE TABLE [dbo].[cr_Destinations](
		[Destination_ID] [int] IDENTITY(1,1) NOT NULL,
		[Destination] [nvarchar](50) NOT NULL,
	 CONSTRAINT [PK_cr_Destination] PRIMARY KEY CLUSTERED
	(
		[Destination_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

END
