USE [MinistryPlatform]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Donation_Non_Cash_Assets](
	[Non_Cash_Asset_Type_ID] [int] IDENTITY(1,1) NOT NULL,
	[Non_Cash_Asset_Type] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Donation_Non_Cash_Assets] PRIMARY KEY CLUSTERED 
(
	[Non_Cash_Asset_Type_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO